task_level: "node"
model: "GCN"
dataset: 
  name: "Cora"
  self_loop: True # when self_loop is True, the graph will be forced to remove redundant edges
test_rounds: 5
save_path: "logs"
log_interval: 50

# learning parameters
params:
  seed: 41
  epochs: 500
  init_lr: 1.e-2
  lr_reduce_factor: 0.9
  lr_schedule_patience: 25
  min_lr: 1.e-5
  weight_decay: 5.e-4
  print_epoch_interval: 10
  max_time: 24

# model parameters
net_params:
  num_layers: 3
  hidden_dim: 200
  out_dim: 7
  dropout: 0.35
  # use_bias: True
  batch_norm: True
  relu: True
  residual: True
  mlp_readout: False

#evaluator parameters
evaluator_params:
  name: Top_K_Evaluator
  k: 1

#loss parameters
loss_params:
  name: CrossEntropyLoss